packages:
  - htop
  - python3
  - python3-pip
  - curl
  - vim
ssh_port: 22
firewall_rules:
  - name: "Allow SSH"
    port: 22
    protocol: tcp
  - name: "Allow HTTP"
    port: 80
    protocol: tcp
  - name: "Allow HTTPS"
    port: 443
    protocol: tcp
