---
- name: Activer et configurer le port3 sur FortiGate
  hosts: fortigate
  collections:
    - fortinet.fortios
  connection: httpapi
  gather_facts: no

  vars:
    vdom: "root"
    ansible_httpapi_use_ssl: no
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 80

  tasks:
    - name: Activer le port3 et lui assigner une IP statique
      fortios_system_interface:
        vdom: "{{ vdom }}"
        state: present
        system_interface:
          name: "port3"
          mode: "static"
          ip: "192.168.20.1 255.255.255.0"
          allowaccess: 
            - ping
            - ssh
            - https
            - http
          role: "lan"
          type: "physical"
