---
- name: Exemple du module user
  hosts: nodes
  become: true

  tasks:
    - name: Créer un groupe de déploiement
      group:
        name: deploygroup
        state: present

    - name: Créer un utilisateur pour le déploiement
      user:
        name: deployuser
        comment: "Utilisateur pour le déploiement"
        shell: /bin/bash
        groups: deploygroup
        state: present
