---
# tasks file for webserver
- name: Installer Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Démarrer Nginx
  ansible.builtin.command:
    cmd: service nginx start


- name: Déployer le fichier de configuration Nginx
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: Redémarrer Nginx