all:
  children:
    nodes:
      hosts:
        node4:
          ansible_host: 192.168.60.14
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
        node5:
          ansible_host: 192.168.60.15
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
        node6:
          ansible_host: 192.168.60.16
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible:
      hosts:
        ansible:
          ansible_host: 192.168.60.10
          ansible_user: root
          ansible_ssh_private_key_file: /root/.ssh/id_rsa
